// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27wA1EUWfK3NIh1EQ_T3x_7bZRW7Vcyo',
    appId: '1:631323860980:web:3d829f1552a3c82db363a1',
    messagingSenderId: '631323860980',
    projectId: 'recipe-7a618',
    authDomain: 'recipe-7a618.firebaseapp.com',
    storageBucket: 'recipe-7a618.appspot.com',
    measurementId: 'G-6YJJCBVRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8tFo4zitR2Ng9TZrAbL0xiiAf4ZRJYA',
    appId: '1:631323860980:android:9e19177497694df4b363a1',
    messagingSenderId: '631323860980',
    projectId: 'recipe-7a618',
    storageBucket: 'recipe-7a618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDblbGd5jc9Z8-UKP_G3rSZy3rf1MAic2k',
    appId: '1:631323860980:ios:2f28832073efaac5b363a1',
    messagingSenderId: '631323860980',
    projectId: 'recipe-7a618',
    storageBucket: 'recipe-7a618.appspot.com',
    iosBundleId: 'com.example.geminiIoTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDblbGd5jc9Z8-UKP_G3rSZy3rf1MAic2k',
    appId: '1:631323860980:ios:2f28832073efaac5b363a1',
    messagingSenderId: '631323860980',
    projectId: 'recipe-7a618',
    storageBucket: 'recipe-7a618.appspot.com',
    iosBundleId: 'com.example.geminiIoTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27wA1EUWfK3NIh1EQ_T3x_7bZRW7Vcyo',
    appId: '1:631323860980:web:3b3773ec37da1acfb363a1',
    messagingSenderId: '631323860980',
    projectId: 'recipe-7a618',
    authDomain: 'recipe-7a618.firebaseapp.com',
    storageBucket: 'recipe-7a618.appspot.com',
    measurementId: 'G-H32MK3PYXE',
  );

}